name: build
on: push

jobs:
  build:
    strategy:
      matrix:
        rename: [0, 1]
      fail-fast: false
    runs-on: ubuntu-latest
    name: Build RENAME=${{ matrix.rename }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Java 17
        uses: actions/setup-java@v3
        with:
          distribution: adopt-hotspot
          java-version: 17
          cache: gradle
      - name: Use Bad File
        if: ${{ matrix.rename == 1 }}
        run: cp -f rename_patch.mk app/src/main/cpp/foobar/Android.mk
      - name: Build
        run: ./gradlew assembleDebug
